#' Global Variables Declaration 
#' 
#' This script declares global variables to suppress notes about undefined global
#' variables during the package build process. These variables are used throughout
#' the package but are not defined in a way that R CMD check recognizes.
#' This declaration avoids the "no visible binding for global variable" notes.
#'
#' @name global-variables
NULL

utils::globalVariables(c("prob", 
                         "section", 
                         "y",
                         "M_X_ci_lower", 
                         "M_X_ci_upper", 
                         "M_X_estimate", 
                         "M_X_pvalue", 
                         "M_Y_pvalue", 
                         "X",
                         "X_M_pvalue", 
                         "X_latent", 
                         "Y_M_ci_lower", 
                         "Y_M_ci_upper", 
                         "Y_M_estimate", 
                         "Y_M_pvalue",
                         "Y_X_ci_lower", 
                         "Y_X_ci_upper", 
                         "Y_X_estimate", 
                         "Y_X_pvalue", 
                         "Y_X_std_es_ci_lower",
                         "Y_X_std_es_ci_upper", 
                         "Y_X_std_es_estimate", 
                         "ci.lower", 
                         "ci.upper", 
                         "ci_lower",
                         "ci_upper", 
                         "conclusion", 
                         "conf.high", 
                         "conf.low", 
                         "cor.test", 
                         "data", 
                         "data_processed",
                         "data_raw", 
                         "decision_correlation_M_X", 
                         "decision_correlation_Y_M",
                         "decision_correlation_Y_X", 
                         "decision_regression_ols", 
                         "decision_ttest",
                         "effect_size_extracted", 
                         "effect_sizes", 
                         "effect_sizes_with_publication_bias",
                         "est", 
                         "estimate", 
                         "fit", 
                         "hist", 
                         "indirect_pvalue", 
                         "iteration", 
                         "lhs", 
                         "lm", 
                         "map", 
                         "mean_score",
                         "model", 
                         "model_type", 
                         "op", 
                         "p.value", 
                         "p_pub", 
                         "pop_model", 
                         "pop_model_label", 
                         "published",
                         "rhs", 
                         "rnorm", 
                         "runif", 
                         "score", 
                         "sd", 
                         "se", 
                         "std.error", 
                         "t.test", 
                         "temp_id", 
                         "term", 
                         "y"))

